name: flutter_template
description: A Flutter project template with common dependencies.
publish_to: "none" # 防止意外发布到 pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 常用依赖
  dio: ^5.4.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  logger: ^2.3.0

  # 常见 UI 组件
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  # 修改包名工具
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  
  #图片路径
  assets:
    - images/

